version: "3"
services:
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "note_chest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpass"
      POSTGRES_HOST: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
#  service_fronted:
#    build: ./service/fronted
#    container_name: service_fronted
#    depends_on:
#      - postgres
#      - service_user
#      - service_link
#      - service_note
#    ports:
#      - 5000:5000
  service_user:
    build: ./service/user
    container_name: service_user
    depends_on:
      - postgres
    ports:
      - 5001:5000
  service_link:
    build: ./service/link
    container_name: service_link
    depends_on:
      - postgres
      - service_user
    ports:
      - 5002:5000
  service_note:
    build: ./service/note
    container_name: service_note
    depends_on:
      - postgres
      - service_user
      - service_link
    ports:
      - 5003:5000