version: "3"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: "user_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pgpass"
      POSTGRES_HOST: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: ./service/user
    depends_on:
      - postgres
    ports:
      - "5000:5000"
